baseURL = "https://lazywasabi.com/"
languageCode = "en-us"
title = "LazyWasabi"
Paginate = 10
rssLimit = 10

[params]
  description = "LazyWasabi's Blog"

[permalinks]
  posts = "/blog/:slug/"
  pages = "/:slug/"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "à¸«à¸™à¹‰à¸²à¹à¸£à¸"
    pre = "ğŸ“"
    url = "/"
    weight = 1
    [menu.main.params]
      class = "lg:hidden"
  [[menu.main]]
    name = "à¸šà¸¥à¹‡à¸­à¸"
    pre = "ğŸ“"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "à¹€à¸à¸µà¹ˆà¸¢à¸§à¸à¸±à¸š"
    pre = "ğŸ£"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "à¹€à¸ªà¸µà¸¢à¸‡à¸™à¸³à¸—à¸²à¸‡à¹„à¸—à¸¢ ETS2/ATS"
    pre = "ğŸšš"
    url = "/ets2thainav/"
    weight = 4
  [[menu.main]]
    name = "à¸•à¸´à¸”à¸•à¹ˆà¸­"
    pre = "ğŸ“§"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.twitter]
    enableDNT = true
  [privacy.vimeo]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
